"""added list of channels for bot

Revision ID: 079aea70ef89
Revises: d128711db5f7
Create Date: 2023-02-06 17:08:05.919811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079aea70ef89'
down_revision = 'd128711db5f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgbots', sa.Column('channels', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tgbots', 'channels')
    # ### end Alembic commands ###
