"""update column twich

Revision ID: 0be683aa28f5
Revises: 0ced0dd159df
Create Date: 2023-02-04 19:01:37.888138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be683aa28f5'
down_revision = '0ced0dd159df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_actions', sa.Column('twitch_id', sa.Integer(), nullable=False))
    op.drop_constraint('twitch_actions_twich_id_fkey', 'twitch_actions', type_='foreignkey')
    op.create_foreign_key(None, 'twitch_actions', 'twitch', ['twitch_id'], ['id'])
    op.drop_column('twitch_actions', 'twich_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitch_actions', sa.Column('twich_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'twitch_actions', type_='foreignkey')
    op.create_foreign_key('twitch_actions_twich_id_fkey', 'twitch_actions', 'twitch', ['twich_id'], ['id'])
    op.drop_column('twitch_actions', 'twitch_id')
    # ### end Alembic commands ###
