"""added goodgame model

Revision ID: 3124a0f41412
Revises: cde250d879d2
Create Date: 2023-03-06 11:16:21.403477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3124a0f41412'
down_revision = 'cde250d879d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goodgame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('channel_link', sa.String(), nullable=False),
    sa.Column('is_live_now', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('tgbot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_text', sa.String(), nullable=True),
    sa.Column('action_image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tgbot_id'], ['tgbots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_name', 'tgbot_id')
    )
    op.create_table('goodgame_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goodgame_id', sa.Integer(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['goodgame_id'], ['goodgame.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goodgame_notifications')
    op.drop_table('goodgame')
    # ### end Alembic commands ###
