"""add connector twitch

Revision ID: 44aa9cf553c9
Revises: 53ae37637f64
Create Date: 2023-02-04 16:14:55.481433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44aa9cf553c9'
down_revision = '53ae37637f64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('broadcaster_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitch_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twich_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('action_name', sa.String(), nullable=False),
    sa.Column('action_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['twich_id'], ['twitch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitch_actions_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitch_action_id', sa.Integer(), nullable=False),
    sa.Column('attachment_type', sa.String(), nullable=False),
    sa.Column('attachment_filename', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['twitch_action_id'], ['twitch_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitch_actions_attachments')
    op.drop_table('twitch_actions')
    op.drop_table('twitch')
    # ### end Alembic commands ###
