"""update logs table

Revision ID: ac34357c4ce8
Revises: 3a236e0eed0b
Create Date: 2023-02-06 14:45:42.728056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac34357c4ce8'
down_revision = '3a236e0eed0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgbots_logs', sa.Column('message_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tgbots_logs', 'message_type')
    # ### end Alembic commands ###
