"""add uuid4 twitch webhook

Revision ID: bdf3ecc4d421
Revises: 079aea70ef89
Create Date: 2023-02-07 11:18:44.678871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf3ecc4d421'
down_revision = '079aea70ef89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhooks', sa.Column('twitch_webhook_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhooks', 'twitch_webhook_id')
    # ### end Alembic commands ###
