"""added unique constraint for vkplay tbl

Revision ID: c7451024bd20
Revises: a1b8e1b6d2af
Create Date: 2023-03-02 10:42:53.311084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7451024bd20'
down_revision = 'a1b8e1b6d2af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'vkplay_live', ['channel_name', 'tgbot_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vkplay_live', type_='unique')
    # ### end Alembic commands ###
