"""vkplay notification table

Revision ID: cde250d879d2
Revises: c7451024bd20
Create Date: 2023-03-03 15:38:40.363861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde250d879d2'
down_revision = 'c7451024bd20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vkplay_live_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vkplay_live_id', sa.Integer(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['vkplay_live_id'], ['vkplay_live.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vkplay_live_notifications')
    # ### end Alembic commands ###
